import { Metadata } from 'next';
import './globals.css'
import { twMerge } from 'tailwind-merge';
import { Varela_Round } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const varelaRound = Varela_Round({
  subsets: ['hebrew','latin'],
  weight: ['400'],
  display: 'swap',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl">
      <body className={twMerge(varelaRound.className, "text-base antialiased")}>{children}</body>
    </html>
  )
}




